### ISSUE TITLE
Erste Tipps

### ISSUE THREAD

**Issue by JouleFirewolf** [MartinPhilipp/Islandwar#1]
Nach dem ersten mal anspielen deines Spieles hab ich schon den ersten Tipp. Die Spielmechanik des Spieles ist schon einmal sehr gut. Die Tutorials führen einen auch gut in das Spiel ein. Jedoch empfehle ich die Fahrtgeschwindigkeit der Schiffe zu erhöhen, oder wenn sogar möglich eine Option wo man den Zeitverlauf des Spieles selber einstellen kann. 
LG Julia

**Comment by MartinPhilipp** [comment]
Thank you for your advice! We will implement your suggestions for improvements in the next version. If you have any further ideas for enhancements, please write an issue.

**Comment by MartinPhilipp** [comment]
Your suggestions have been implemented. You can change the speed of the game in the menu settings.
